### ISSUE TITLE
Any plans to support repeating tasks?

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#11]
Just installed Sleek. Nice work! Any plans to support repeating tasks?

**Comment by ransome1** [comment]
I was thinking about it and some other todo.txt apps already have it implemented. That could actually be 0.7.0 material here. I'll get back to you as soon as there are any news.

**Comment by velardevines** [comment]
Great, thanks!  If it helps, I am able to help test.

**Comment by ransome1** [comment]
@velardevines . There is some progress on this feature, but I am stuck with a question I would like to address to you.

Let's say there is a todo that is due today. And in the past you defined that this todo has a recurrance of one week. I was thinking it makes sense, to duplicate the old todo and leave it untouched. The new todo would then have the same attributes, except that the due date would be that of the old todo but plus 7 days. And also the start date of the new todo would be set equal to the due date of the old todo. I hope that doesn't sound to confusing ;)

Alternatively, instead of duplicating a todo, we could also change the old todo and adjust the start und due date according to whatever recurrance had been defined.

What do you think is the most common use case?

@jason-mehmel, not sure if this feature is of value for you, but if maybe you have an opinion here too. Would be great.

**Comment by jason-mehmel** [comment]
It's an interesting point. I tend to do habit tracking or recurring tasks in things other than todo.txt, but I can imagine a situation where it would be useful.

Working through the question... either: a) generating a new task line copied from the previous based on some repeating logic, or b) editing the line with repeating logic.

In the case of A) benefits would be having each task line as it's own granular reminder. If the repeating is happening a lot, then you'll see them stack up, which would cause you to re-evaluate the commitment. There could also be some interesting tracking and reporting that could happen... "I have mowed the lawn 475 times since adding it as a commitment!" (Or at least marking it done 475 times.)

Some downsides could be a very large text file if either the code goes wrong, or if the user selects a repetition cycle and doesn't maintain it... (setting repetition for every second vs. every day, etc.)

In the case of B) you miss out on the benefits above, but you also miss out on the risks. It's a lot cleaner and more minimal.

I can imagine some specific projects or plans that could benefit some repetition but aren't something as repetitive as 'make the bed...' like a quarterly check-in with a colleague that you want to track at a task level.

All of that said, I don't know if a repeating task best fits the todo.txt tool. I'd default to just using my calendar! In my case I use a bullet journal for meeting notes as my paper inbox before things get to todo.txt, and a habit tracker for the month lives in there as well, so I'm ticking off boxes on things like daily meditation.

For me, the appeal and benefit of todo.txt is that it's actually inherently limited; it's not a one-stop productivity method. It's only there for me in the GTD sense of collect, review, and process. So I'm okay with having things that get done outside of that system if they don't require that kind of flow.

That was a whole ramble. Sorry. I hope it helps at least frame the request and next steps in some interesting ways.

**Comment by ransome1** [comment]
@velardevines, I just uploaded a pre-release that contains a recurrence picker, you can download it here: https://github.com/ransome1/sleek/releases/tag/v0.7.0-Alpha

**Some things for you to know**
- Recurrences can only be selected when a due date has been selected first. Actually the recurrence picker is invisible until this happens
- You can set the recurrence per text input using "rec:" and adding d (daily, due date +1), w (weekly, due date +7), m (monthly, due date +30), y (yearly, due date +365) for the recurrence you wish. I know that the monthly recurrence of 30 days might be a bit tricky on months like February or December. In future versions I might add exceptions for those months to be more precise.
- I avoided more complexity like for instance every second week and so on, as this would add a lot of complexity to the interface and the syntax and I am not sure if the benefit for the user of this would be big enough. As @jason-mehmel added, the todo.txt syntax (at least for now) is perhaps not meant for really complex task planning. 
- I totally misspelled "Recurrence" in the code and the translation files but will fix that ;)

Implementing it wasn't trivial, but I hope it works at least roughly. Please don't be angry if you'll find a big bug. That could actually happen.

I'm looking forward hearing from you.

**Comment by velardevines** [comment]
I'll download 0.7.0. Thanks for working on this feature. 

Setting the new due date based on the old due date is a good approach. 

Another option is to set the new due date based on the completion date. Both options have advantages. 

I'll download the release and do some testing. 

--Bill

**Comment by velardevines** [comment]
I've checked the recurring feature but not extensively. Only one unexpected outcome at this point. I created a task with due date two days in the future and with a weekly recurrence. If I check the task as done before the due date then no new task is created. It seems a new task should be created regardless of when the task is completed. 

--Bill

**Comment by ransome1** [comment]
Good point I didn't have this use case in mind. Let me see what I can do. Thanks for the feedback so far!
