### ISSUE TITLE
[Question] Display/work on only today's tasks

### ISSUE THREAD

**Issue by ExtremeCoolDude** [ransome1/sleek#127]
**Did you check if a similar feature request has already been reported?**
Yes

**Is your feature request related to a problem? Please describe.**
Display only today's tasks in filter list (completed/not completed)

**Describe the solution you'd like**

Hello, I don't know where else to ask this question, sorry. I did read wiki and searched past issues, couldn't find anything. 

I would like to : 

-- On a recurring task, display only today's tasks. If the task was uncompleted yesterday, discard it, jump to today's task. Currently if I mark as done on a task that was uncompleted yesterday, it marks as done on yesterday, and not on today.

![image](https://user-images.githubusercontent.com/50034073/118341922-dd48c400-b540-11eb-9ffd-dc8f1c65d5ae.png)

**Describe alternatives you've considered**

-- Discard past todo's only work on today's todo list. Bonus points if I can store history of what was done/what wasn't on a specific date.

**Comment by ransome1** [comment]
Hi @ExtremeCoolDude . Sorry, I wasn't at the keyboard for two weeks and am now checking Github.

I read your feature request, but I don't really understand what exactly you're asking for or what exactly the issue is.

**Comment by ransome1** [comment]
@ExtremeCoolDude, if your question is still relevant, please feel free to get back to me here. As soon as I understand the issue, I'll try to helpout where I can.

**Comment by ExtremeCoolDude** [comment]
Sorry about that. This has to be the fastest 20 days I've ever spent. I guess the question can be best illustrated by doing the following steps :

1. Setup a recurring task.
2. Wait for 1 day. (or change date)

As you can see on the interface, now there are 2 tasks. Instead of something like : 

![image](https://user-images.githubusercontent.com/50034073/120732138-8a8d7700-c504-11eb-8ac6-25166ecaad2b.png)


Now if we do the following : 
1. Mark as done on the task.

We can see that the task is done on a _previous_ date.

The main confusion : 

The tasks keep adding up on a recurring task if it isn't marked as done daily. 

![image](https://user-images.githubusercontent.com/50034073/118341922-dd48c400-b540-11eb-9ffd-dc8f1c65d5ae.png)

**Comment by ransome1** [comment]
Hi @ExtremeCoolDude, can you please post the actual todos you create and that then get created in a wrong way? For instance: 
Completing
`2020-06-04 201 rec:d`
creates:
`2021-06-04 201 due:2021-06-05 rec:d`

Also, did you check if this behavior also occurrs in in the latest release v1.0.5? Please don't be surprised, but the auto creation has been removed recently after a lengthy discussion in another thread here on Github.

**Comment by ExtremeCoolDude** [comment]
Sorry about that, all I needed was `due:2021-06-04` filter (today's date) to view today's taks alone and mark them as done on the correct date .  I downloaded the 1.0.5 deb file, the recurring task still works. The  results on the main interface  aren't being displayed properly I guess which got me confused.

For eg first change the settings in the sleek : 
![image](https://user-images.githubusercontent.com/50034073/120753655-3c3f9e80-c52b-11eb-9114-e648301ea15b.png)

Now: 
1. Setup a recurring task.
2. Change the date one day forward.
3. Open Sleek
4. Close Sleek
5. Change the date one day forward.
6. Open Sleek 
7. Mark a task as done using the settings in the picture.

Expected : Task to be marked as done on today .
What happens: Task gets marked on the day when the task  was skipped.


The todo.txt seems to be unaffected. I'm sorry for  being stupid I guess  for reporting the multiple tasks since the tasks aren't being created again, its just on a different date due to it being recurring. Unchecking to hide "overdue" in the settings hides them. 

Also the issue on the steps on this comment doesn't exist if one simply relies on `due:` filter instead of sleek's settings.

**Comment by ransome1** [comment]
Hi @ExtremeCoolDude

`Setup a recurring task.`
- Can you please post the exact task
- Do you do this in sleek? 3. implies sleek is closed in this moment
- is there a start date set? If so to which day?
- is there a due date set? If so to which day?

`Change the date one day forward.`
- is this done in sleek?
- From which day do you switch to which day?

**Comment by ExtremeCoolDude** [comment]
Hi, I edited the above comment.

**Comment by ransome1** [comment]
- [x] Setup a recurring task. 2021-06-04 204 due:2021-06-04 rec:d on sleek and close sleek. 
- [x] Change the system (Operating system settings) date one day forward. i.e. 2021-06-05
- [x] Open Sleek
- [x] Close Sleek
- [x] Change the OS date (system date) one day forward once again. i.e. 2021-06-06
- [x] Open Sleek
- [ ] Mark a task as done using the settings in the picture. **-> this now is not possible, because the todo created in 1. is overdue and therfor won't be display.** 

Anyhow, when I set the toggle on "Overdue", the formerly hidden todo will be shown and when I then mark it as complete the result is
- the old todo, which is marked as done today (OS is still set to `2021-06-02`): `x 2021-06-06 2021-06-04 204 due:2021-06-04 rec:d`
- a new todo is being created: `2021-06-06 204 due:2021-06-07 rec:d`

To my understanding this behavior is correct. I assume you get a different result on your system?

**Comment by ExtremeCoolDude** [comment]
Yup, the last step in your comment cannot be done since it won't display, but on my pc it does display and looks like : 

![image](https://user-images.githubusercontent.com/50034073/120816225-4932b100-c570-11eb-835f-9236f96b537c.png)

**Comment by ransome1** [comment]
Your screenshot is different (due date icon is missing) from the example you provided in 1. (`2021-06-04 204 due:2021-06-04 rec:d`).

I set my computer to `2021-06-04` and repeated your steps without the due date (`2021-06-04 204 rec:d`), did the closing/starting and changing the os date two times.

Now it's `2021-06-06` and I mark the todo as complete with these results:
- The old todo: `x 2021-06-06 2021-06-04 204 rec:d`
- The new todo: `2021-06-06 204 due:2021-06-07 rec:d`

The new todo now will be hidden, because the `due in the future` button is disabled.

So far it is still as it is expected to work :/

**Comment by ExtremeCoolDude** [comment]
"Your screenshot is different (due date icon is missing) from the example you provided in 1. (2021-06-04 204 due:2021-06-04 rec:d)." 

Yup, however if I toggle "overdue" to be enabled : 

![image](https://user-images.githubusercontent.com/50034073/120819825-ab40e580-c573-11eb-87eb-a69ab2db29d8.png)
Idk how it explain it, basically I missed a few days and then when I fired up sleek, the due date missing screenshot is happening. It should not display those. I guess I'll just use due: filter.
