### ISSUE TITLE
settings for todo.txt file specific

### ISSUE THREAD

**Issue by amigo421** [ransome1/sleek#153]
is it currently possible to keep the settings along side with todo.txt or any other way to keep file-specific settings? 
i'm using a few files for different scenarios and that is not useful to go into the settings and switch those each time to open different files

**Comment by ransome1** [comment]
Hi @amigo421, this is not possible and I don't think it's going to be a feature soon. As a workaround and if you are on Windows, you can try downloading the zipped portable version of sleek and duplicate it a couple of times. Each unzipped folder contains the application itself and separate preferences file. I havn't tried it out myself, but if you do, let me know if it works.

**Comment by amigo421** [comment]
> Hi @amigo421, this is not possible and I don't think it's going to be a feature soon. As a workaround and if you are on Windows, you can try downloading the zipped portable version of sleek and duplicate it a couple of times. Each unzipped folder contains the application itself and a separate preferences file. I havn't tried it out myself, but if you do, let me know if it works.

that is an enough solution for me.
thanks!

**Comment by amigo421** [comment]
won't create new one , just a couple more questions:
1. is it possible/planned a custom colors setting for the rendering in priorities ? 
2. the order of the tasks within a priority groups : supposed the order matches to order in todo file? is it possible/planned to drag the items to re-order in the file?

**Comment by ransome1** [comment]
1. As of now I don't have any plans to make any color customization a feature of sleek
2. Within the priority group the next sorting method is by due date and then according to the order in file. Reorder by drag and drop has been discussed here (https://github.com/ransome1/sleek/issues/18) and remains as a lose idea on my personal backlog. But it's connected to a lot of conceptional work and development hours and won't (at least on my side) be worked on on the short term. My focus right now is to improve stability and performance and make sleek more maintainable, instead of adding new features.
