### ISSUE TITLE
Content disappears if todo.txt is edited externally

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#155]
**To Reproduce**
- Open a todo.txt in sleek.
- Edit the same file in a text editor.

**Expected behavior**
- Sleek updates its contents to reflect changes (as before).

**Actual behavior**
- All content is hidden in sleek as if the file is empty. Clicking reset filters has no effect.
![200](https://user-images.githubusercontent.com/78097210/120855768-32e02180-c57f-11eb-8ac4-637aa0859e4b.png)
- Content is shown again on reloading sleek.

**Desktop (please complete the following information):**
 - Windows
 - Latest sleek from Github.

**Comment by 9z0** [comment]
Side thing: please add "Actual behavior" to bug report template.

**Comment by ransome1** [comment]
Interesting, in particularly because the file watcher received quite some fine tuning and testing over the last couple of weeks. I quickly checked it on my Linux where it worked flawless, but I will check in on my Win 10 VM tomorrow. 

Is the file you're editing synced by something like Dropbox, Syncthing or similar?

**Comment by 9z0** [comment]
> Is the file you're editing synced by something like Dropbox, Syncthing or similar?

Yes but the behavior happens even after it is disabled.

I noticed now that it happens with VS Code but not some other editors and only if you switch immediately to sleek after clicking save 😕

**Comment by ransome1** [comment]
@9z0, I can't reproduce it, not even on Windows 10 with VS Code:

https://user-images.githubusercontent.com/11188741/120896644-c28adc00-c622-11eb-8036-446b899e40f3.mp4

The same happens when I switch to sleek immediately after saving the document.

**Comment by 9z0** [comment]
OK. I tried to reproduce your reproduction. I found the following:

It seems to be about reaching Sleek before the save process is complete. So:

- It doesn't occur if the file is small. A few lines will be saved too fast it seems. Try hundreds (or thousands) of todos.
- I measured ~2.5s between the disappearance of the dirty marker and the switch in your video. The switch needs to be really fast. Reflexive CTRL+S ALT+TAB. Gamer-like. 😉

**Comment by ransome1** [comment]
Alright, would you mind closing the issue, if it is resolved?

**Comment by 9z0** [comment]
How is it resolved? 😕

I can try to wait a little while before switching as a workaround if you think it is unsolvable.

**Comment by ransome1** [comment]
It certainly is somehow resolvable, but I can't be putting effort into an issue I can't even reproduce and that is an edge case.

**Comment by 9z0** [comment]
Still not reproducible after my post-video comment?

If so, I can close the issue.

**Comment by ransome1** [comment]
Yes, I have gave it my best shots (and I used to be a Gamer) but wasn't able to break it. Not even with my dummy todo list with around 500 entries and when I quadrupled the entries to over two thousand it still worked. But again, I'm not saying I don't believe you. 

Even if I was able to reproduce it with 5000+ entries: Do you consider this workflow relevant? The typical use case imo is not that I use sleek and a text editor at the same time, working on my todos and do rapid tabbing between them. 

A typical use case that might be affected by this would be if a sync service like Dropbox or Syncthing is involved, breaking the file watcher because of unexpected or slow file hanlding of VS Code. Actually this used to be a nasty issue in the past that led to the replacement of nodes native file watcher implementation with a more reliable one.

**Comment by 9z0** [comment]
I understand. It is just that when _you_ are that edge case, it doesn't make it less of an issue that no one else has it, I guess.

Thanks for your effort. 👍
