### ISSUE TITLE
Markdown code block issue

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#191]
`<space>+text` inside a code block is parsed as project. For example:

```
(A) `This is code +text`
```

**Comment by zerodat** [comment]
This is a little tricky.  As you know, todo.txt is intended to be a very simple format with minimal syntax.  Since Markdown is not part of the todo.txt "standard", any quoting inside the text of a todo is not recognized as special by todo.txt.  In practical terms, that means that the jsTodoTxt parser doesn't treat quotes as special and doesn't recognize Markdown constructs in todos.  I think that is why the ` +word` is being recognized as a project, before the Markdown processing even begins.   As I would expect, the closing quote is being included as part of the project name.

**Comment by ransome1** [comment]
@zerodat you're right about this. 

@9z0 I agree it is an issue, but I would raise the question if this is a relevant use case that can really cause pain to sleeks users and would justify the work of figuring out a solution either on sleeks side or maybe even involving upstream.

**Comment by 9z0** [comment]
@zerodat , @ransome1 

Thanks for explanations. No, it is not a major issue. I would of course prefer a fix, but I can work around it until a feasible solution presents itself.

Should I close the issue?

**Comment by ransome1** [comment]
@9z0 up to you. Again I wouldn't want to work on it but I don't mind adding it to the backlog.

**Comment by 9z0** [comment]
OK, I would appreciate if you make a note of it somewhere for reference, and I will close this issue.

**Comment by 9z0** [comment]
OK, I would appreciate if you made a note of it somewhere for reference, and I will close this issue.
