### ISSUE TITLE
Sleek connects to "clark.uberspace.de" even if analytics are unchecked

### ISSUE THREAD

**Issue by asakura42** [ransome1/sleek#196]
As `netstat -tup` prints, when I open sleek, electron estabilishes connection to `clark.uberspace.de` and keeps it. I didn't found this domain in your repo and in electron sources, so my question is: what can it be? Some dependency need this connection maybe?

**Comment by ransome1** [comment]
Hi @asakura42 on each start sleek pings my Matomo instance once so I can keep track of the general usage, which is important because sleek is distributed through several channels and without this I have no indication of its actual usage.

 he event and error logging will only transfer metrics once you opt in in sleeks settings. You can take a look at the Privacy.MD for all details.

**Comment by asakura42** [comment]
@ransome1 Thanks. I see in mitmproxy that it's your website. By the way as data paranoid I often warn about all that things. Thank you for reply and for so cute application!

**Comment by ransome1** [comment]
Data paranoid myself here, so I totally understand. Which is also the reason why I host everything myself fully open source. I wouldn't dare to expose sleeks users to anything like Google, Microsoft, Adobe or whatever.

**Comment by ransome1** [comment]
No wait, Github is Microsoft nowadays, right? ;) So that was only half true.

**Comment by comminutus** [comment]
It'd still be nice to disable this connection to robbfolio.de .  As a privacy enthusiast, this raises some minor flags.  It's not to say Sleek users shouldn't trust you, it's more about limiting attack surfaces.  For example, if the data you are collecting is breached, it along with other pieces of information might lead to someone connecting too many dots.  Can you add an option to disable this?  Should I open a new ticket?
