### ISSUE TITLE
Print view

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#212]
**Did you check if a similar feature request has already been reported?**
Yes, i could find nothing similar.

**Is your feature request related to a problem? Please describe.**
I can not alway take my notebook with me. Sometimes it would be good if i could print out a filter selection to have all open todos with me out in the fields.

**Describe the solution you'd like**
Str+P opens standard print dialog

**Describe alternatives you've considered**
Export filter selection to export.txt and print it via Notepad++

**Comment by ransome1** [comment]
@Saturo78 I'm going to look into it. A simple print view reduced to the filters and visible todos should be quite simple to implement. I'll ping you here once we have a first preview.

**Comment by ransome1** [comment]
@Saturo78 I'm not 100% sure what you mean with "filter selection", but I assume you mean the selected filters (if any) and the todos filtered by that selection, right? Everything else wouldn't propably make sense anyhow.

I added a simple print styling, that removes all elements of the GUI that are not needed for printing. You can test it in the pre release: https://github.com/ransome1/sleek/releases/tag/v1.1.0-rc.2

Call the print dialog either with the keyboard shortcut Ctrl/CMD+P or via the application menu (press Alt in sleek).

I'm looking forward for your feedback.

**Comment by Saturo78** [comment]
Thank you very much for the quick response!
I have had a first look.
In daymode it is usable, in nightmood the dark background is printed to and looks very much like a screenshot.
Generally I think it could be more a plaintext list. 
Maybe with lines between the entrys to have the possibility to made notes by hand.
The filter section on top needs much space. The context of the filter line on to of the printout should be be sufficient.

My first try was to print out directly from the todo.txt with notepad++ but i additionally need the option to filter the tasks.

**Comment by ransome1** [comment]
Thanks for the feedback. 
`In daymode it is usable, in nightmood the dark background is printed to and looks very much like a screenshot.`
You're right I havn't really tested in in dark mode. And I think it doesn't make any sense to print in dark mode, which is why I will try to render the print in bright mode per default. 

`Generally I think it could be more a plaintext list.`

It would be possible to print evrything in greyscale. 

`Maybe with lines between the entrys to have the possibility to made notes by hand.`

I don't know, this sounds like a very unique pattern how you would use it but could be annoying for others. Especially because it would produce more paper.

`The filter section on top needs much space.`

I think in general everything could be a little more compact.

`The context of the filter line on to of the printout should be be sufficient.`

What do you mean by that?

**Comment by Saturo78** [comment]
> `The context of the filter line on to of the printout should be be sufficient.`
> 
> What do you mean by that?

Instead of the filter menu on top of the page a single line with the content of the search field:

E.g.:
"Filter: due < today+6b and +project"

**Comment by ransome1** [comment]
@Saturo78 there have been minor adjustments to the print view: https://github.com/ransome1/sleek/releases/tag/v1.1.0-rc.4
- It is grayscaled now (printer friendly)
- The filter drawer is hidden
- The search bar is shown

If there aren't any major issues with this I would be releasing it to see if there is any usage on this. Only then it makes sense for me to spend more time on this feature, which I hope you'll understand.

**Comment by Saturo78** [comment]
It looks okay, maybe you could remove the due:date popup which is hoovering over the entrys.
For me you don´t need to put energy in this issue.
I have found a good workaround using notepad++ and the plugin Linefilter3 
https://www.seelisoft.net/Linefilter3/

So i get a realy oldschool plaintext printout :o)

**Comment by ransome1** [comment]
I think for now we're good and I'm going to close it. If there will be feedback on this function, we can always reopen it or a new issue will be created.
