### ISSUE TITLE
Feature Request: adaptive filtering of the filter tray

### ISSUE THREAD

**Issue by jason-mehmel** [ransome1/sleek#22]
This is similar to an earlier feature request, though that one was limited to just the process of adding new tasks. (For anyone else reading, basically, that function is reducing the possible contexts and projects you can apply reduce as you type. So if you type '[at]1' for example, you'll only see the contexts that still apply based on that criteria. I use numbers for some important contexts, so it's a very useful shorthand for me. I've also got projects that start with some similar wording, so it's handy to filter down to only the ones that apply.)

This is something different though. I'm wondering if what's visible in the filter tray can be reduced according to the filters that apply.

For example, if I select [at]someday, I would love to see only those projects and contexts that apply to any of the tasks that are inside that filter. I've got tags in there like +read +gaming +watch, etc.

So, following that example, let's say I wanted to see what projects have tasks that are currently captured in the [at]someday context... in this new feature request, I'd click the context in the filter tray **and/or** search for the context in the search bar, and then in the filter tray I'd only see whatever contexts and projects still apply to the current filter. So I'd only see +watch +read, +gaming, instead of everything that is in the file.

In that earlier feature request, I think I said I was okay with just seeing the highlighted contexts in play, but with the amount I have of both contexts and projects, seeing those contexts and projects disappear if they don't match the current filter would be very useful!

**Comment by wsdfhjxc** [comment]
Yes, it's quite reasonable to navigate tags like that. Especially because, in the filter's logical `AND` query mode, clicking a couple of unrelated tags provides no results, so I'd say it's just better to hide the irrelevant tags altogether.

By the way, one additional thing, shouldn't the filter tray's internal query be stringified and also copied to the text input filter bar at the top? I think of it like a global query (doesn't matter if clicked or typed), but now, these two UI elements feel detached.

As a side note, sleek is the only desktop todo app I've found enjoyable to use. I hope that @ransome1 doesn't feel overwhelmed with all the suggestions. I know feature creep is a serious thing to be concerned about when maintaining a project.

**Comment by ransome1** [comment]
Makes sense, that's for sure. There might be an issue with usability though. I for instance have only 8 contexts and 5 projects and my todos mostly have one or, at max, two contexts assigned, often not even a project. I admit, I might be an exotic case. So clicking on one context would, in my case, reduce the filter list to only one entry at one blow and could irritate the user. But then again, we can just try it out and see for ourselves. When I find some time this week, I will change the filter, push a test release and we can figure it out.

Also @wsdfhjxc , pushing the selected filters into the search string is just consistent and should be easy to implement. The only challenge here is to automatically adjust the selected filters again, once you start removing them from the search string.

But let's start step by step.

PS: I feel as overwhelmed, as I feel happy to see that you guys are actually using sleek. Which is a great thing. I just hope people won't be too disappointed if work on feature requests won't start right away. After all it's just a creative hobby on top of a full blown full time job.

**Comment by ransome1** [comment]
@jason-mehmel , @wsdfhjxc , feel free to check out Revision 195 from Snap Stores Edge Channel, it includes the switch to adaptive filtering. Let me know how it works for you.

**Comment by jason-mehmel** [comment]
It works wonderfully! This is basically the last feature I was desperate for regarding using this app. I've got lots more ideas for other functionalities, but this to me is the icing on the cake of a clean, robust, and simple todo.txt app.

(Also, regarding usability, when I do a search in the search bar, it doesn't reduce the filter tray. **I don't think it should!** I think this is a great way for someone to look for a string of text, be it contexts, projects, or anything, without affecting the filter tray.)

@ransome1 You've _seen_ my todo.txt... so you might imagine how nice it is to be able to clean up the visuals as I drill down with filters!

It's a form of generating a live report. When I click on my [at]someday context, I'll see only those projects that apply, which can be a quick way to get a sense of how much I've committed to in that context.

Also, @ransome1 I think we're more than comfortable waiting for feature requests... if anything, I've found you to be incredibly responsive and quick with applying the ones that have come up so far!

Thank you for all you do.

**Comment by ransome1** [comment]
@jason-mehmel . I think you and @wsdfhjxc were right after all, not only does it makes sense and feels logical, but it also hasn't a negative effect on the usability as I was expecting.

I remember your todo list and especially the long filter list. Thinking about it, I would like to point out, that the filter drawer is now resizable in it's width. So in case you have a wide screen and you don't want to scroll your filters so much, you can widen it. Just drag the border between the drawer and the todo table area. That setting will be persisted.

**Comment by wsdfhjxc** [comment]
Thank you for implementing this, and for the resizable drawer. That's really awesome!

Also, as for the idea of synchronizing the filter tray and the search bar, I meant that it could be implemented in a way so that no particular filtering capabilities are sacrificed (freely mixed tags and keywords, etc.). But since the search bar parses provided queries strictly in a todo.txt format, it's currently not possible to achieve this like I imagined. It'd require tokenizing search queries, and then applying filters individually. So, I'll just abandon that idea for now, and maybe experiment in my local fork at some point.

**Comment by ransome1** [comment]
@wsdfhjxc, let me know if you achieve something useful in your fork. Thanks again for your contribution on the template function.

@jason-mehmel, I just published the adaptive filtering as part of 0.8.0. Thanks for your push.
