### ISSUE TITLE
Breaks the original structure of the text file

### ISSUE THREAD

**Issue by heX16** [ransome1/sleek#247]
The format implies manual editing, and I arrange the fields as I like. The editor should not change them.

The format implies synchronization through file exchange - this causes constant "synchronization conflicts". I have to do the merge manually. after modification in such an editor many changes occur - it becomes difficult to do the merge.

Arbitrary changes in the content of records that I have not even changed, indicates the poor quality of the library which performs parsing and text reassembly. Poor work of the **core** - it undermines the credibility of the project.

Translated with www.DeepL.com/Translator (free version)

**Comment by ransome1** [comment]
@heX16 I understand the issue, but as you correctly assumed a third party library is being used for the parsing process which rearranges the structure.

Due to many things, especially a lack of man power and time on my side, there is no initiative at the moment moving away from that library.

If you're having issues with this behavior, there is not much we can do about it at the moment and I would actually advice you to look for a different GUI.
