### ISSUE TITLE
A filter box next to Projects/Contexts

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#270]
**Situation**:
- many projects/contexts.

**Need**:
- Finding a particular project to click without cumbersome manual sifting.
- Not remembering exact project wording (or which character it begins with), etc.

**Suggested solution**:
- A filter-as-you-type box next to the headings "Projects"/"Contexts"
- It can be hidden by default until the number of projects/contexts exceeds a certain value.

![a](https://user-images.githubusercontent.com/78097210/134793441-495e6842-bd1d-4de8-8b28-b56ecda910d5.png)

**Comment by ransome1** [comment]
@9z0 thanks for the suggestion. I understand your use case here but I personally use the full text search we already implemented and due to @zerodat greats improvements on it, this works quite well on manipulating the filter drawer as well. Especially in combination with the "Empty filters" setting turned off. Which will reduce the shown filter while you write.

I don't really see the necessity to introduce a second search element to the app.

**Comment by 9z0** [comment]
No problem. I'll close the issue.
