### ISSUE TITLE
Allow sorting by creation date

### ISSUE THREAD

**Issue by gdevenyi** [ransome1/sleek#296]
Often I add an entry, and then realize I want to edit/change it, however, due to the sorting rules it immediately disappears.

I'd like to have a sorting option for creation date, so I can find it.

In addition, helpful in finding "old" todos that need to be deleted or completed.

**Comment by aubreyz** [comment]
The text file should always be in creation order, so creation order should be an unsorted mode.

**Comment by ransome1** [comment]
> The text file should always be in creation order, so creation order should be an unsorted mode.

sleek tries to alter the text file as little as possible, especially the sorting is not touched. All this happens in sleek interface.

I think what @gdevenyi is asking for is a new sorting method by creation date, which is automatically added by sleek on a new todo. But it does not necessarily mean the list is unsorted (as is in file).

**Comment by gdevenyi** [comment]
Yes I'm asking for a sorting mehod in display. Definitely don't want to modify the file, as per my comments in the other thread.

**Comment by ransome1** [comment]
Hey @gdevenyi , @aubreyz . Can I throw this pre release at you for some proper testing? It contains the "Creation date" sorting method. keep in mind that for being sorted by creation date, the todo needs to have one and if it's not there it is suppose to be sorted last. Let me know what you think.

https://github.com/ransome1/sleek/releases/tag/v1.1.4-rc.1

**Comment by ransome1** [comment]
@gdevenyi @aubreyz here comes another try: https://github.com/ransome1/sleek/releases/tag/v1.1.4-rc.1

Please feel free to check if the sorting according to creation date is working as expected.

**Comment by aubreyz** [comment]
I am away from Windows for a few days but will test later. 

To be honest given I work across several Todo systems some of which use creation dates and others not and because it wastes a lot of space and processing time I tend to switch off creation dates (in simpletask for example), I would not find sorting by creation date (with separate sorting by items without a date) that useful. 

Sorting by original file order (which is probably a better surrogate for the same thing) is definitely useful though.

**Comment by gdevenyi** [comment]
@ransome1 works as expected so far

**Comment by dnngll** [comment]
Hello,

just a quick observation/feature request/bug-report concerning the sort-order, since it seems that it is currently being worked on:

The way "creation date" it is being handled right now, is that all todos, that happen on one specific day, are put together, and then sorted in file order. That leads to Sleek turning

![2021 12 15, 16 39 37 Window](https://user-images.githubusercontent.com/12801866/146217771-3cdc089f-dc94-48d2-a4f1-c914193fb8fc.png)

into

![2021 12 15, 16 39 10 Window](https://user-images.githubusercontent.com/12801866/146217884-eb17b8f3-1178-469d-bacb-0f40f6dbf462.png)

. It would be really helpful, if there was also an option to sort by file-order. This would then be either "line 1, line 2, line 3..." or "last line, second-last line, third-last line...". In the case above "1, 2, 3..." or "9, 8, 7...".

Also, is there a way to reverse the sort order?

Thanks!

**Comment by ransome1** [comment]
@dnngll thanks for your suggestion. The sorting behavior you're describing is intended. If you're looking for a way to invert the sorting method, you can open a new feature request, so we can add it to the backlog :)

@aubreyz @gdevenyi a `sorting by file order` would mean some adjustments on the UI as well. As far as I understand it, `sorting by file order` should be not a drag and drop item (like in the Sort by block) but more a toggle. Which when turned to on kind of hides the "Sort by" block, as this now would not have a function any more. This would be a separate feature request though. Otherwise if we piggyback this FR we will never close it :D

With the release of 1.1.4 I would like to close here.

**Comment by dnngll** [comment]
> @dnngll thanks for your suggestion. The sorting behavior you're describing is intended. If you're looking for a way to invert the sorting method, you can open a new feature request, so we can add it to the backlog :)

Perfect, thanks. Done: https://github.com/ransome1/sleek/issues/306
