### ISSUE TITLE
Allow *.todo (or even all) file extension(s)

### ISSUE THREAD

**Issue by evert-mouw** [ransome1/sleek#303]
Instead of using `mystuff.todo.txt` I would like to use `mystuff.todo` so *todo* files are more easily recognized by their extension. But Sleek doesn't allow me to open such files. I know, it goes against the "todo.**txt**" convention, but I like my *.todo* naming scheme and maybe I'm not alone :-)

**Comment by ransome1** [comment]
@evert-mouw we already scaled sleek to support .md as it turned out to be quite useful for some users. So technically it wouldn't be a biggy to support .todo files. 

As far as Google knows, .todo files are being used as databases for an apparantly abondoned project (https://filext.com/file-extension/TODO). If there is a specification on how .todo files need to look like and if this differs from the todo.txt fomat, we might have an issue here though.

But what I would like to also discuss in this context would be pros and cons of not just adding .todo, but opening up sleek for all file extensions. Initially I had concerns about this being a security issue. Maybe we can hijack this thread and gather some thoughts about this.

**Comment by ransome1** [comment]
@evert-mouw fyi I added *.done to the supported file extensions and it can be used in the next release.

**Comment by evert-mouw** [comment]
Thanks a lot! Sorry for only noticing this now (serious personal circumstances). I'm happy with Sleek :-)
