### ISSUE TITLE
textarea edit - broke from recent upgrade

### ISSUE THREAD

**Issue by marshmanGit** [ransome1/sleek#31]
Textarea editing - looks like your most recent update broke this feature.
It is not stripping line feeds when saving to a file therefore it creates a todo for every line.
thx
marshall

**Comment by ransome1** [comment]
Hi @marshmanGit . I checked and found a glitch that could have been responsible for the behavior you're describing.

Could you check if the problem persists in this pre release? https://github.com/ransome1/sleek/releases/tag/v0.8.5-Beta

Please check the adding and editing todo function.

**Comment by marshmanGit** [comment]
Best I can tell it seems to be working fine.  I do have a recommendation however.  I see where you strip \r\n from the content being saved ( and for good reason ).  The problem with doing "only" that is this.
Example of my input:
Line 1
Line 2
Example of input when I edit the todo:
Line1 Line2

This rolls back around to my initial comment where you can substitute \r\n with some other character during the save operation which should not invalidate todo rules and then replace it with \r\n upon edit which will preserve textarea input formatting.

While most may simply use the input and not the textarea input then it is likely not of interest but since you did add the textarea input then it would be worth while preserving format.  Nonetheless, I can certainly work with the current methods and the update is great and I appreciate your work.
Thank you!!!!!

**Comment by ransome1** [comment]
@marshmanGit, could you check this release? https://github.com/ransome1/sleek/releases/tag/v0.8.6-Alpha

Let me know if this works as expected. And if it does feel free to give it some testing.

**Comment by marshmanGit** [comment]
Just tested the 0.8.6 alpha and we are not there yet.  But getting very close.
See the attached PDF
[sample1_sleek.pdf](https://github.com/ransome1/sleek/files/5882525/sample1_sleek.pdf)

**Comment by ransome1** [comment]
Could douple check if you're actually using 0.8.6? Because I just downloaded the AppImage and it works differently like you described in the PDF.

It is suppose to work like this:
Step 1: Adding 1 new todo with several line breaks
![step1](https://user-images.githubusercontent.com/11188741/106043823-364e3280-60df-11eb-8520-a56b60662efe.png)

Step 2: Combining the lines into one line for the list entry
![step2](https://user-images.githubusercontent.com/11188741/106043913-567df180-60df-11eb-9344-daaff6145b1d.png)

Step 3: Reopen the todo
![step3](https://user-images.githubusercontent.com/11188741/106043947-61388680-60df-11eb-9068-d85623ec8aa3.png)

Which release do you download btw? Then I can reupload just the one you need for the testing.

**Comment by marshmanGit** [comment]
Yep, something got in the way of launching 0.8.6.  I tested just now and
works GREAT!!!!
Sorry about that.

**Comment by ransome1** [comment]
Has been released in 0.8.6 on all channels. Thanks again for pointing out these improvements.
