### ISSUE TITLE
Support for Markdown-style URL syntax (automated)

### ISSUE THREAD

**Issue by amigo421** [ransome1/sleek#387]
The great feature: markdown-style URL syntax allows store a bookmarks . 
thanks a lot for this!

this is a suggestion to slightly automate such bookmarks storing (potential scenario):
- as usual: insert some (valid) URL (fake address) "https://mypage.com" into todo item and save this 
- improvement: sleek (on save event, in background process) try to auto-retrieve webpage title (e.g. "My page title" from the web and convert plain URL text in note into formatted URL syntax with retrieved title and previously entered URL: 

> `[My page title](https://mypage.com)`

**Comment by ransome1** [comment]
@amigo421 I like the idea. The only obstacle could be very long titles. Often those are cluttered with waste or attempts to manipulate search engines. Do you have any idea how to deal with that?

**Comment by amigo421** [comment]
@ransome1 tried to use this. 
- retrieval works in most cases. sometimes , the title is not extracted from parameterized urls, but this is not a big problem. I'll try to collect a few ones later to check 
- about the functionality: I mean a little bit other. You extracted the title and show this in todo list view, but editing mode still contains plain url. I mean real replacement from  url to markdown-style format with square brackets and parentheses to keep in the source (todo.txt) the processed title/url
`[My page title](https://mypage.com)`

**Comment by ransome1** [comment]
Let me see what I can do about the markdown conversion. 

Another concern with this I can think of, can be users not wanting or expecting sleek to alter their inputs. So maybe it might be a good idea to disable it by default.

**Comment by stianmandarin** [comment]
This is a really good start! I agree that having the links converted to markdown instead of keeping them as links only would be preferable.

In my head:
1. Convert links to markdown
2. Once converted to markdown, the link is considered processed and Sleek won't fetch the title again
3. Also, it would be great with an option to specify max numbers of chars allowed in title

**Comment by ransome1** [comment]
@amigo421 @stianmandarin unfortunately what appeared as a quick win turned out to be more complex as expected. I was hoping I could use the markdown parser to retrieve website data asynchronously. But it turned out not to be possible at this point. So we need a different approach and as this feature isn't high priority, I needed to parked it temporarily. I'll get back to you, when there is progress again.

**Comment by stianmandarin** [comment]
@ransome1 No worries, mate!

**Comment by aisbergde** [comment]
If this will be implemented, then I suggest an option to save links 
* as they are
* using markdown syntax
* using AsciiDoc url macro syntax 
https://docs.asciidoctor.org/asciidoc/latest/macros/url-macro/ like
`https://asciidoctor.org[]`

I switched from Markdown to AsciiDoc for all my notes and I am very happy. Especially because of includes and xref, which makes it much easier to link between notes and to reuse content.

Of course, when opening links, all 3 syntax used to store the link should be supported. It should be possible to mix. Because tasks are created using different ways. For example I often use Android Simpletask to share a link, and the link will be as supported by Simpletask.
