### ISSUE TITLE
"Delete" does not work

### ISSUE THREAD

**Issue by Grydpype** [ransome1/sleek#429]
**Is it an actual bug?**
I believe so.

**Did you check if the bug has already been reported?**
I did not see this issue in the bugs listed

**Describe the bug**
It is not possible to delete a task using the option menu on the right mouse button.

**To Reproduce**
1. Select any issue with the right mouse button
2. choose "Delete" in the options menu
3. task will not be deleted.

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
Task should be deleted from todo.txt

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Version of sleek : 1.2.8
 - Source: Flathub

**Comment by CPUGPU** [comment]
Confirmed.  1.2.8 appimage on xubuntu 20.04.5 LTS

**Comment by dlaidig** [comment]
I also just noticed this. However, for me, instead of the task under the mouse cursor, some other task was deleted. Can you check if this is also the case for you?

**Comment by zerodat** [comment]
@dlaidig, I think you are right.  In my tests, the delete removes **the first todo in the file**, rather than the one you selected with the mouse.  (This is especially hard to see if you happen to have completed todos in the file and you aren't showing completed todos.  If the first todo in the todo.txt file is already completed, you won't see any todo change in the GUI.)  The best way to see what is being deleted is to save a copy of your todo.txt file, then do a delete in sleek, and then `diff todo.txt todo.txt.save`.

@ransome1, I submitted PR #433 to fix this bug.

**Comment by ransome1** [comment]
@Grydpype @dlaidig @CPUGPU thanks for reporting it and @zerodat thanks for fixing it. The fix is part if the next release.

**Comment by rzelnik** [comment]
I confirm that in v1.2.9-rc.1 the task deletion works as expected.

**Comment by dlaidig** [comment]
It also worked for me. :)

**Comment by ransome1** [comment]
With this release you should also be able to use `del` or `backspace` to delete a selected todo: https://github.com/ransome1/sleek/releases/tag/v1.2.9-rc.2
