### ISSUE TITLE
Will Sleek run on Mediatek processor? 

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#43]
Can any of the distributions be installed on a device using a Mediatek processor? In this case a Lenovo Chromebook Duet.  Excuse my lack of understanding about the various Linux distributions. 

Thank you.

**Comment by ransome1** [comment]
Hi @velardevines. Propably not out of the box. There are workarounds to get for instance the Debian build running on ChromeOS (Part 3 of https://www.computerworld.com/article/3314739/linux-apps-on-chrome-os-an-easy-to-follow-guide.html), but your device seems to have an ARM processor and the binaries here on Github are all build on a regular AMD64 machine. So my guess is this won't work. 

But instead of using the binaries here on Github, it seems to be possible to get Snap (that's the Ubuntu application store) running on ChromeOS: https://forum.snapcraft.io/t/how-to-install-snap-on-any-chromebook-chromeos-with-crostini-fully-working-guide/15734

On Snap, sleek is distributed for the most major cpu architectures, also on ARM. So if you get Snap running, sleek should be available to you.

Can't vouch for it, but you could give it a try and let me know.

Best

**Comment by velardevines** [comment]
Thanks for the suggestions @ransome1

**Comment by ransome1** [comment]
You're welcome. If you're going to try it out, I would be interested in the outcome. Let me know.
