### ISSUE TITLE
Can't open nextcloud todo.txt file

### ISSUE THREAD

**Issue by hoshi411** [ransome1/sleek#453]
Running Sleek version 1.3.0 on Ubuntu Gnome  22.04.1 LTS

I have a todo.txt file hosted in my nextcloud.
I have the files able to access mounted on my Gnome desktop.

In Sleek I click on "open todo.txt" blue button.

I am able to navigate to my todo.txt file mounted on my desktop.

I click "open" after selecting the file.

I expect it to now be synced with Sleek app but nothing at all happens.

**Comment by hoshi411** [comment]
I solved the problem.

I uninstalled the Flatpak version of Sleek and installed 1.3.0 .deb file.

I can now sync with nexcloud todo.txt file.

I am very sad that I cannot use the flatpak version.

**Comment by hoshi411** [comment]
I also want to say.

You DEVs are amazing and thank you for this amazing solution which has basically saved my life.

Thank you so much .

**Comment by NanoExplorer** [comment]
Could it be a flatpak issue? I'm not an expert at flatpak, but since it's a sandbox it could be that it doesn't give sleek access. I think flatpak doesn't allow access to mounted volumes by default, and you mentioned you had mounted the nextcloud server. (https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory)

My first instinct was that it could be related to #443 , although #443 also affects version 1.3.0 so probably not.
