### ISSUE TITLE
Special character prevents parsing of project and context tags

### ISSUE THREAD

**Issue by kettenfett** [ransome1/sleek#463]
Project and context tags are not parsed correctly in this instance (see image). i also tried `@lop`. Still not recognized.

![grafik](https://user-images.githubusercontent.com/23098362/217792150-f1d8dc5f-f337-4e2c-94e2-3276ef06f77b.png)

when I click the task, I noticed, there is a square symbol, that i didn't write, but was probably copy&pasted from MS excel:
`[..]due:2023-02-28+lop `

This character  is preventing the parsing of tags. Parsing works, when I remove it.
The character is actually a delimiter of some kind. (it shows up as "DLE" in Notepad++ with "View all characters on")

Can you filter out this character or improve parsing tags when it shows up in front of the '+' or '@' ?

![grafik](https://user-images.githubusercontent.com/23098362/217793869-535f83f2-cb7b-4aa9-a481-2842bfe563ef.png)

edit: i just noticed it also prevents the parsing of the due date.

**Comment by ransome1** [comment]
I'm not sure if it is a good idea to filter out characters based on a single use case. What is a problematic character to you, might be very relevant to others.

The todo.txt rules state that in order to parse a context for instance it must be prepend by a space and the @ sign. So I'm afraid it's probably your duty to get those characters out of the file.

Have you tried using this file in other todo.txt apps? I'm curious if those are capable of filtering this character.

**Comment by kettenfett** [comment]
@ransome1 
I now realised, the appearance of the symbol doesn't have anything to do with inserting text from other programs. It's actually inserted by sleek itself, whenever the task is expanded with
![grafik](https://user-images.githubusercontent.com/23098362/220343380-8893159b-b36f-4425-8468-378c3464684b.png)
and in this expanded view the ENTER key is is used to create newlines.

For every ENTER one square symbol is inserted.

**Comment by ransome1** [comment]
With the [new implementation](https://github.com/ransome1/sleek/discussions/501) this method has not changed. We still need a delimiter saved in the line in order to restore the line breaks in the multi line text field.

However a couple of things have been implemented differently. Feel free to just try it out. Maybe it resolves the issue for you: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev17

I'm collecting feedback for this feature here: https://github.com/ransome1/sleek/discussions/551
