### ISSUE TITLE
More flexible sorting

### ISSUE THREAD

**Issue by ekaterina-o** [ransome1/sleek#465]
It would be great to make sorting more flexible to choose sort order for every field. For example, I'd like to see tasks without date at the top of the list and completed tasks lower sorted by date in descending order. Now it's impossible to get. I also would like to save such order to the file.

**Comment by ransome1** [comment]
I reviewed this feature request, but cannot really extract precise requirements. As stated in the template for feature requests, I can only work on requests, which have a certain level of detail. Please feel free to start a discussion, in order to talk about the details: https://github.com/ransome1/sleek/discussions

Also, the latest developer preview of sleek's version 2.0 has a new sorting system, that you can check out. It looks like this:
<img width="577" alt="Bildschirmfoto 2023-08-29 um 16 40 56" src="https://github.com/ransome1/sleek/assets/11188741/5924ffe3-6fb7-4486-a6c2-64c7fb63deb9">

You are able to use almost all available attributes for the sorting and within each group, you can revert the sorting. You can download it here: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev5
