### ISSUE TITLE
No start date even when appendStartDate is set to true

### ISSUE THREAD

**Issue by pprw** [ransome1/sleek#508]
**Is it an actual bug?**
It is a bug because sleek documentation described another behavior

**Did you check if the bug has already been reported?**
yes

**Describe the bug**

1. Sleek does not append a start date for todos out of the box for me.

I manually edited the user-preferences.json to change 
```
"appendStartDate":false
``` 
to 
```
"appendStartDate":true
```

This did not change anything.

2.  The relevant part of the documentation is not coherent.

https://github.com/ransome1/sleek/wiki/Hidden-preferences,-custom-variables-and-command-line-parameters
> 
> Append start date on todo creation
> 
> Per default sleek will append a start date (today's date) to a new todo. Setting this to false will prevent this.
> 
> appendStartDate: Boolean (default: false)

"default: false" seems to be indicating sleek is not suppose to append by default creation date which is the default behavior described just above...

**To Reproduce**
1. create todo
2. check on the file if there is a creation date

**Do you see any error entries in sleeks developer tools?**
no

**Expected behavior**
a creation date should be created

**Desktop (please complete the following information):**
 - OS: debian stable
 - Version of sleek [e.g. 0.9.8] : 1.3.1
 - Source: Flathub

**Comment by ransome1** [comment]
@pprw there is an old feature request still open, in which this bug was discussed: https://github.com/ransome1/sleek/issues/401

But let's use this proper bug report of yours to tackle the issue.

In the upcoming developer preview of v2.0 (sleek is currently being rewritten in React) this issue is solved. In fact there is going to be an option in the GUI to disable or enable this function. Once `developer preview 4` is released, feel free to test it and provide feedback.

**Comment by dlaidig** [comment]
Isn't this the same as #432?

**Comment by ransome1** [comment]
@dlaidig you're right. Sorry, I overlooked it. @pprw will be finished in #432
