### ISSUE TITLE
Error in completion format

### ISSUE THREAD

**Issue by antoniopaolini** [ransome1/sleek#538]
## Bug Report

**App Version:** [2.0.0-dev13]

**Platform:** [macOS ]

**Installation Method:** [Direct Download ]

**Bug Description:**
If I mark task completed the 1.3.1 version save it moving the priority in property, like `pri:C`, to be clear.
The 2.0.0-dev13 instead modify the row by adding `x` in front but leave the priority in place. This conflict with the  format rule n°2 for complete task, that say: [Rule 2: The date of completion appears directly after the x, separated by a space.](https://github.com/todotxt/todo.txt#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space)

**Steps to Reproduce:**
1. Write down a task with priority
2. mark as completed
3. open the todo.txt file with a text editor or another todo.txt app (in the screenshots is TodoTxtMac)

**Screenshots:**
![Screenshot 2023-10-02 alle 01 34 52 copia](https://github.com/ransome1/sleek/assets/60228211/69eb199b-eb7b-40dd-bfa4-1552bb9cc0e9)

![Screenshot 2023-10-02 alle 01 50 33 copia](https://github.com/ransome1/sleek/assets/60228211/c35b4fd5-0f96-4df5-993a-dfda4171a6af)

**System Information:**
- OS Version: [macOS Sonoma]
- Processor: [M1

**Reproducibility:**
- [Always /]

**Impact:**
- [Major]

**Comment by ransome1** [comment]
@antoniopaolini this should be fixed in https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev15. Could you please check if it works on your side?

It has a limitation though. If you restore a todo with `pri:`, it will **not** remove the extension itself.

So if `x Test pri:A` is marked as incomplete again, it will create `(A) Test pri:A`. This is due to the todo.txt parser not being able to remove extensions yet. [It is addressed with them.](https://github.com/jmhobbs/jsTodoTxt/issues/49)

**Comment by antoniopaolini** [comment]
> @antoniopaolini this should be fixed in https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev15. Could you please check if it works on your side?
> 
> It has a limitation though. If you restore a todo with `pri:`, it will **not** remove the extension itself.

Yes, it's works.
