### ISSUE TITLE
notify only for some TODOs, like those matching a particular search filter

### ISSUE THREAD

**Issue by bughunter2** [ransome1/sleek#542]
## Feature Request

**Description:**
Please see the use case.

**Use Case:**
Various use cases: one may want to reduce the amount of notifications, and so only get notifications for A-priority TODO items, or maybe those of a particular project they're currently working on (and keep out notifications of other items), or only those they marked with a '+notify' project, or perhaps one wants to keep certain notes more private than others (and prevent so-called 'shoulder surfing', for example at work). In those cases, it makes sense to have configurable notifications.

**Implementation Details:**
Suggest to add a configurable 'search filter', and only show notifications for TODO items that match the search filter. That wouldn't be too tedious to implement and it's very flexible for users. This way, the todo.txt format is left as-is and the todo.txt will NOT get cluttered by the configurable notifications.

Consider this a nice-to-have, not must-have.

**Comment by ransome1** [comment]
@bughunter2 we might be able to combine this with the search filter feature, which is currently being developed: https://github.com/ransome1/sleek/issues/179

The easiest way of implementing this would really be, as you suggested, to fire a notification once a todo matches one of the `search filters`. But this might lead to some confusion on users side why this happens, because it is not really intuitive. But we would be able to add a notification icon next to the search filter entry in the list. It is turned off per default. I enabled a notification will be sent once a new or existing todo matches this particular filter.

**Comment by bughunter2** [comment]
@ransome1 Wonderful. Seems like a good way to fuse these ideas. That way it automatically becomes intuitive (since it's a conscious choice) for those who turn on notifications for a particular search filter.

**Comment by ransome1** [comment]
Will be developed over at https://github.com/ransome1/sleek/issues/179
