### ISSUE TITLE
Multi-select operations

### ISSUE THREAD

**Issue by intrepidsilence** [ransome1/sleek#56]
It would be great to be able to select multiple items and then:
Copy
Add/Remove Tags
Add/Remove Context
Add/Remove/Change up,down Priority
Mark Done/In Progress

I really like the sleek app so far and want to say thank you for your efforts.  Great start!

**Comment by ransome1** [comment]
Hi @intrepidsilence, the latest work on bulk changing contexts, projects and priorities does not solve your particular request here, but it could be of help for you. If you like, feel free and participate on the testing and try out this development version of v1.0.5: https://github.com/ransome1/sleek/releases/tag/v1.0.5-1

If you have feedback for me, please share it here: https://github.com/ransome1/sleek/issues/47

**Comment by intrepidsilence** [comment]
Thanks

**Comment by 9z0** [comment]
Possible targets of actions:
- all todos in the file.
- all visible/current filtered (including lazy-loaded only or *all*?)
- on selected

**Comment by Saturo78** [comment]
I would really like this feature to have the posibility  to move all tasks that i could´t complete, to the next day much quicker as now.

**Comment by aleksfadini** [comment]
I think this feature is really essential for big lists.
Thank you for bringing it up

**Comment by peterm02019** [comment]
Thanks for the great work on sleek so far. It is looking and feeling really good!

I'd like to add my vote for this feature too. It would be incredibly useful for moving (for example) all the weekend todos I did not manage to complete this weekend straight to next weekend by selecting them all and then changing all their dates at once. There may be 10 or more items, depending on how successfully things went this weekend!

As a suggestion for the interface mechanism, selecting multiple items by right click & drag works very well in other software I use regularly. I realise that a right click on an item in sleek currently brings up a context menu, but this should still work ok with the drag requirement. If the right click is dragged within 100mS, then it is a multi select attempt rather than a context menu request. If it is clicked and not moved for more than 100mS, then it is a context menu request.

Once there is a selection made, then right clicks on further unselected items would add them to the multiple selection, or remove items from the selection if they are already selected.

What do others think? This is currently the only 'bug' in sleek for me.

Thanks & have a great day!

**Comment by ransome1** [comment]
@aisbergde @intrepidsilence @peterm02019 @9z0 @aleksfadini @Saturo78 

I'm currently working on a bulk operations feature. Although still in an early phase, I can use some testing and feedback for the way this has been implemented so far. The proof of concept has been added to this pre-release: https://github.com/ransome1/sleek/releases/tag/v1.3.1-rc.3

Let me know what you think.

**Bulk operations**
Multiple todos can be selected by pressing `Ctrl/Meta` key and clicking the todo row. Right mouse click will then expose the context menu, which allows bulk operations. Furthermore a new button `Bulk operations` has been added, which provides bulk operations to add and delete contexts and projects.

**This PoC provides bulk operations for:**
- Priorities
- Copy
- Delete
- Add and remove `contexts` and `projects`

**Work in progress**
- Due dates
- Recurrences
- Mark as complete or incomplete
- Selecting multiple rows with `Shift` and `Arrow` keys and shortcut `Ctrl/Meta + A` to select all visible todos
- Translation, refactoring, test cases

**Comment by smellymoo** [comment]
this still doesn't seem to be available? it seems weird that you can't bulk select todos to then delete them.

**Comment by aisbergde** [comment]
My workflow: I sync my todo files between PC and smartphone. On my smartphone I use SimpleTask which has all features, I need, including multi-select :-)

**Comment by reinaldoaru** [comment]
this have been discarded?

**Comment by smellymoo** [comment]
I mean, normal is you long tap, then it enters selection mode, then you can do whatever to all the selected items.
