### ISSUE TITLE
[Sandbox] Handling of done.txt file

### ISSUE THREAD

**Issue by TriggerDingus** [ransome1/sleek#564]
**App Version:** 2.0.1

**Platform:** Linux

**Installation Method:** Flathub

**Bug Description:**
Prior to the rewrite, my archive for both my Active and Done tasks was (and still is) located at **/media/bob/TheDataHoard/ToDo.txt/todo_done.txt**.
Upon installing version 2.0.1 and performing "ToDos > Archive completed todos", the app provided the following dialog box:
![image](https://github.com/ransome1/sleek/assets/75340371/e5bf0e06-30e9-45e4-a52e-0b27dd5083cb)

Assuming all is well, I clicked on "Archive". Problem is, I found it didn't archive to my chosen location. Assuming I needed to update a setting somewhere in the new version, I searched the Settings and found nowhere to indicate my Archive file storage location. The application apparently doesn't assume the same location as the currently-open ToDo list and assumes it gets stored in my flatpak app directory. 

Here is a global search I performed where you'll find my old chosen archive along with the file created by the new version stored in my flatpak app directory:
![image](https://github.com/ransome1/sleek/assets/75340371/be43211e-7a97-4123-a674-d639a1d330ba)

**Comment by ransome1** [comment]
@TriggerDingus The title of this bug reports implies, sleek did prompt for the storage location of the done file in the past. That has never been the case. Prior to 2.x sleek simply archived the done file into the same location as the todo.txt file.

Let me try to explain what is happening here: Prior to the rewrite sleek was simply accessing large parts of the file system.  Like that sleek could just add `/home/TriggerDingus/Todo/todo.txt` to its config and work with it. This is not what Flatpak wants, since it requires the app to access large parts of your file system. From a security point of view, I understand. Since 2.0. sleek is now obeying the Flatpak sandbox system a bit more. It now does not access your file system directly any more. So when you use the file chooser (as part of the so called portals), it chooses the desired file, but as some kind of an alias, which mirrors the original with a copy in the sandbox ... or something like that ;) I havn't fully digged into how it works precisely. But since sleek is being distributed to so many platform, all having their own sandbox systems, it's hard to find the time to figure all these things out.

However, as for the done file sleek simply chooses the same location of the todo.txt file and just replaces the todo.txt with done.txt. Both is now located in the sandbox. But the todo.txt file is connected, with that alias, with the original file. The done file of course is not. It just lives in the sandbox.

I have to admit, that the current configuration of the Flatpak gives good reason to ask these questions and as soon as I find the time, I will look into how we can improve the user experience here.

As for a quick workaround: To change the location of the done.txt file, you can right click on the file tab, use the file chooser and select the desired done.txt file. Let me know if this already solves the issue at hand.
<img width="708" alt="Bildschirmfoto 2023-11-02 um 7 37 41 PM" src="https://github.com/ransome1/sleek/assets/11188741/564eceb8-c054-4836-a0e3-6b3571688f4b">

**Comment by TriggerDingus** [comment]
Thanks for the thoughtful response. To be honest, it was a year or two ago that I did my archive in the older versions so I didn't recall how it found the right folder, so it makes sense it put it in the same location as my ToDo.txt file. 
I tried your workaround and just noticed the toggle for "show file tabs" isn't working for me. I tried both the toggle and the switch within settings but I can't get it to show the file tabs. Guessing it might be a permissions issue, I tried turning on all file system permissions for the Sleek Flatpak but that didn't work either. Ideas?

![image](https://github.com/ransome1/sleek/assets/75340371/86186170-73d8-462c-b7af-a19bf02e9e8f)

**Comment by ransome1** [comment]
With the `Show file tabs` set to true, you need to hide the search in order to see the tabs again. Press `Ctrl + F` to do so. Otherwise just click into the search field and press `Escape`.

Maybe another thing, that needs to be improved from a UX perspective.

**Comment by TriggerDingus** [comment]
> With the `Show file tabs` set to true, you need to hide the search in order to see the tabs again. Click on the magnifier icon or press `Ctrl + F` to do so. Otherwise just click into the search field and press `Escape`.
> 
> Maybe another thing, that needs to be improved from a UX perspective.

Worked. Got my archive set to the existing archive filename/location.

**Comment by TriggerDingus** [comment]
Here's the screen cap:
![image](https://github.com/ransome1/sleek/assets/75340371/d1bd95da-9135-4629-91ce-74add7878f74)

So, the path is showing as a flatpak translation? of the location though not using the naming convention I see in my directory tools or CLI.
I did run a test of the archive and it is putting new completed items in the proper file. Mucho thanks.

**Comment by ransome1** [comment]
You're welcome. I morphed this bug report into an enhancement issue. 

Aim is to find a proper way to get the done.txt file part of the sandboxed environments. This goes at least for Flatpak and Mac App Store apps.

I was thinking of not defining a default path to the done file, but on first archiving, to let the user choose the location of the done.txt file. Like that it would be properly handled in a sandboxed environment.

**Comment by andrei-a-papou** [comment]
Just upgraded to v2.0.2  from 1.x and got bitten by this. Archived TODOs ended up in a generic `done.txt`, which was not desirable. It's good to know you can right-click the tab and change the location of `done.txt`, but that, I think, is hardly discoverable.

> I was thinking of not defining a default path to the done file, but on first archiving, to let the user choose the location of the done.txt file. Like that it would be properly handled in a sandboxed environment.

This sounds like a great idea, IMO!

**Comment by ransome1** [comment]
> I was thinking of not defining a default path to the done file, but on first archiving, to let the user choose the location of the done.txt file. Like that it would be properly handled in a sandboxed environment.

@andrei-a-papou @TriggerDingus this has now been implemented and is available for testing via Flathub. Install it with: `flatpak install --user https://dl.flathub.org/build-repo/66829/com.github.ransome1.sleek.flatpakref`

The behavior is now:
- Open sleek and use the file chooser to open a todo.txt file
- In the navigation you will now find a button for archiving, but the keyboard shortcut and the option in window menu will trigger the same function
- Since you did not select an archiving file yet, sleek should ask you to either open an archive file or to create one
- Once you selected or created the archive file, sleek will immediately ask you if you want to archive
- Archiving should be working now
- Restart sleek and work with the files should still work

Since both files (todo.txt and done.txt) have been added to the app with the file chooser, the Flatpak sandbox now knows these files and will have access to them.

There is one aesthetic drawback. Although you will be working in the desired files, sleek will present you with the sandbox link of the file, which is some kind of alias. So if archiving was successful, sleek will show a cryptic path to which has been archived. 

Can you please play around with this feature and let me know if it works on your side as well?

**Comment by andrei-a-papou** [comment]
@ransome1  I do not use Flatpak so can't test it, but I just played with the enhanced archiving feature and here are some thoughts:

# the toolbar button is great, it definitely helps discoverability -- thank you!
# when sleek asks for location of the done.txt file and I click "Create file", the prepopulated file name is _todo.txt_ (see screenshot below). I propose making it _done.txt_ and preferably switching to the same directory as _todo.txt_ in the file picker (if possible with Electron)
![image](https://github.com/ransome1/sleek/assets/30468319/4965bcfd-2064-4c5e-8044-a9beed580f77)
# when everything is archived and you have an empty file, the Filter and Archive buttons should be disabled, I think:
![image](https://github.com/ransome1/sleek/assets/30468319/a485cc82-e0ac-4f82-8cfd-8e7d4ffe4591)
Currently the Filter button tries to open the left drawer and immediately closes it, which looks a bit jerky. And the Archive button allows you to "archive" non-existent toods and then the app happily reports they've been archived :)

**Comment by ransome1** [comment]
> 2\. I propose making it _done.txt_ and preferably switching to the same directory as _todo.txt_ in the file picker (if possible with Electron)

Yep, makes sense and should be possible to implement.

> when everything is archived and you have an empty file, the Filter and Archive buttons should be disabled, I think:

I agree, if the file is empty we should hide the button. 

> 3\. Currently the Filter button tries to open the left drawer and immediately closes it, which looks a bit jerky.

That might actually be a little bug, I'll look into it.

> 3\. And the Archive button allows you to "archive" non-existent toods and then the app happily reports they've been archived :)

Technically this is correct, but of course this doesn't make a lot of sense. We have some potential here to improve the UX.

Thanks for the feedback.

**Comment by TriggerDingus** [comment]
I'm hoping I'll have some time this weekend to build a test environment in a VM to try it out.
I use the current version heavily every day but I don't want to risk installing the test build on my 'production' system.

**Comment by TriggerDingus** [comment]
Just tried installing the flatpak but received the following error:

error: Can't load uri https://dl.flathub.org/build-repo/66829/com.github.ransome1.sleek.flatpakref: Server returned status 404

I may have missed my opportunity to test, so my apologies for that!

**Comment by ransome1** [comment]
> Just tried installing the flatpak but received the following error:
> 
> error: Can't load uri https://dl.flathub.org/build-repo/66829/com.github.ransome1.sleek.flatpakref: Server returned status 404
> 
> I may have missed my opportunity to test, so my apologies for that!

sorry I only now read your post. I rebuilt it and you should be able to install it with: `flatpak install https://dl.flathub.org/build-repo/68396/com.github.ransome1.sleek.flatpakref`

**Comment by TriggerDingus** [comment]
Looks like it works. It also successfully displays the ToDo.txt file tab and is no longer hidden by the Search bar.

**Comment by ransome1** [comment]
@andrei-a-papou I think all your feedback should have been implemented in the latest pre-release: https://github.com/ransome1/sleek/releases/tag/v2.0.3-rc.5

Feel free to give it some testing, before I finally release all the changes with 2.0.3.

**Comment by andrei-a-papou** [comment]
@ransome1 Things seem to work fine now, thank you! I'll let you know if I notice anything in the future
