### ISSUE TITLE
Improve notification feature

### ISSUE THREAD

**Issue by cu186** [ransome1/sleek#595]
**Description:**
The current notification feature feels particularly useless.
When software opened, many notifications popped up all at once.
It would be nice to occasionally pop up a single notification to remind you of today's unfinished tasks.

**Comment by ransome1** [comment]
@cu186 could you please use the corresponding template for a feature request? Or open a discussion first, in order to work out the precise requirements.

And on a side note you might want to check the behavior of this pre-release: https://github.com/ransome1/sleek/releases/tag/v2.0.3-rc.3

It includes a mechanism, which supresses already sent notifications.

**Comment by cu186** [comment]
I'm sorry. I'll pay attention next time.

**Comment by ransome1** [comment]
> I'm sorry. I'll pay attention next time.

Don't worry, since this is a pre-release, it is very unlikely that you could have known.
