### ISSUE TITLE
Better discoverability for inverted filtering

### ISSUE THREAD

**Issue by andrei-a-papou** [ransome1/sleek#634]
I accidentally just discovered that you can Ctrl-click on a priority badge under "Attributes" tab and "invert" the filtering of todos. E.g. you can search for all todos with a priority of "non-A" this way. I think it's a useful feature (Simpletask offers it as well), but I think some kind of hint in the UI would be useful to help people discover it?

**Comment by ransome1** [comment]
@andrei-a-papou I agree and the usage data confirms your assumption. It is already on the backlog of 2.0.7 (https://github.com/users/ransome1/projects/3/views/1) but I'm glad to use this issue here instead. If you like you can use the feature request template and describe the implementation you would expect.

**Comment by amariusz** [comment]
That's a nice feature! It's probably not documented anywhere?

Mentioning modifier keys with LMB it in https://github.com/ransome1/sleek/wiki/Keyboard-shortcuts could be good enough IMO.

**Comment by ransome1** [comment]
I actually removed the `Ctrl` behavior in 2.0.7. Not because it was hard to find, but foremost because I think it is simply not how these kind of features should work. In the latest released I am proposing a different behavior. If a user hovers a filter button in the attribute drawer, the counter in the badge will change to an icon, which indicates the exclusion.

<img width="214" alt="Screenshot 2024-01-21 at 10 01 10 PM" src="https://github.com/ransome1/sleek/assets/11188741/b9c0425b-7ad1-4e67-b136-8621c652c6e7">

Click on the eye icon will then exclude todos which contain this filter.

**Comment by andrei-a-papou** [comment]
> Click on the eye icon will then exclude todos which contain this filter.

Thank you, works great. Good UX, in my opinion.
