### ISSUE TITLE
Specific filter selection provokes wrong splashscreen

### ISSUE THREAD

**Issue by DeflateAwning** [ransome1/sleek#661]
### Important ###
I'm not sure exactly what I did wrong, but I got sleek into a state where it's really unclear what the filters are. I filtered to something, and then modified the filtered entry such that it doesn't have the filtered string anymore. Filter was performed by clicking the '@' field.

**App Version:** Enter the version number, e.g., 1.2.3
v2.0.9

**Platform:** Windows / macOS / Linux
Linux

**Installation Method:** App Store / Direct Download / Other
deb

Screenshot:
![image](https://github.com/ransome1/sleek/assets/11021263/2df81691-02a2-4064-ab40-457a50870eea)

**Comment by ransome1** [comment]
@DeflateAwning it's impossible for me figure this out from the information I can extract from the bug report. In fact I'm not even sure if I understand most of it. 

Have you tried resetting the filters pressing `Ctrl` and `0`?

**Comment by DeflateAwning** [comment]
I'll open a better ticket if I can reproduce. Ctrl+0 fixed it, thanks

**Comment by ransome1** [comment]
From what I see, it kind of looks like a bug. Because I can see greyed out attributes, but the body says there are no todos in the file. Which of course makes no sense. 

If you can recreate this, you could help me by sending them to me by email: ransome@mailbox.org.

**Comment by DeflateAwning** [comment]
I agree that it's a bug. Can't seem to find a reproduction though. Darn.

**Comment by jason-mehmel** [comment]
I encountered the same error recently!

Ctrl+0 fixed it for me, but if it happens again, I'll see about reporting it!

Possibly useful: I've got 2 different todo.txt files now, and I noticed this when switching between them.

**Comment by ransome1** [comment]
@DeflateAwning I have been thinking about this. In your case my assumption is, that you were filtering your todos by selecting some of the single filters. But this should under no circumstances lead to the point where there is at least one single todo left. In order to filter the results to a point, where the list is literally empty, you would need to (in theory) also exclude a filter. 

So if you are selecting filters down to a single result (let's say `Go to @Work`) you will see the this filter still available:
<img width="77" alt="Screenshot 2024-02-23 at 5 31 49 PM" src="https://github.com/ransome1/sleek/assets/11188741/431795ed-baa7-43f9-8e83-980ea4835c74">

If you just click on the filter the result should be the same `Go to @Work`. But if you now exclude this filter by clicking on the eyelash, you will provoke a list with zero results:
<img width="45" alt="Screenshot 2024-02-23 at 5 33 42 PM" src="https://github.com/ransome1/sleek/assets/11188741/92b6a71e-4e1b-46e3-a4c3-32bf558e9aba">

I really hope that this is what you did, because then I do understand the issue. The fact, this is how it is implemented, but the bug here is the wrong splashscreen:
<img width="192" alt="Screenshot 2024-02-23 at 5 34 54 PM" src="https://github.com/ransome1/sleek/assets/11188741/f4889e12-3d19-49ab-8606-cfa70fbfdefc">

This should say `No todos found` and should also offer a button to reset filter and search. 

I cannot say this happened on your side but I assume it. And I will be able to fix this.

@jason-mehmel : This is something which can happen, when working with 2 files, as long as we haven't implemented separate filter-settings for different todo files. In your case you might have selected a filter in `todo1.txt`, which is not available in `todo2.txt`. This would lead to the same result.

**Comment by ransome1** [comment]
@jason-mehmel @DeflateAwning this pre-release should contain a fix for this issue: https://github.com/ransome1/sleek/releases/tag/v2.0.10-rc.2

Feel free to test it out.
