### ISSUE TITLE
[Windows] Work better with Windows 10 Task Manager bar

### ISSUE THREAD

**Issue by intrepidsilence** [ransome1/sleek#72]
**Is your feature request related to a problem? Please describe.**
If you pin the sleek.exe app to the Task Manager bar in Windows 10 and then click it to open then it opens a second icon in the Task Manager instead of using the pinned icon.

**Describe the solution you'd like**
It would be great if it used the pinned icon like other apps, rather than creating a new one.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by shulist** [comment]
Also if you , <Right-Click> the Sleek taskbar item and open "Sleek" from the pop-up menu it also opens a second instance of the last file.
Expected Behavior: Open one of a list of files, or open the last file if only one is available.

**Comment by ransome1** [comment]
Hi @intrepidsilence, hi @shulist. I am not a Windows user myself, but have it running in a virtual machine. I will briefly look into it, what can be done about this, but can't promise anything.

If you have any knowledge about how to solve these issues on Windows, please feel free to share whatever you know.

**Comment by shulist** [comment]
@ransome1 While I would not classify myself as a windows programmer I do have limited experience.  Unfortunately my typical programming style is brute force and ignorance. However I'd be willing to help out in any way.

**Comment by intrepidsilence** [comment]
@ransome1 Unfortunately it is exactly the opposite for me. I must use Windows and that it where it ends. Sorry I cannot help more in this regard.

**Comment by blumpcus** [comment]
Hi everyone,
I looked further into this.
I don't have a definitive answer but here's what I've found:

- Whenever you open sleek.exe, regardless of the directory you have saved sleek.exe in, it actually unpacks itself to _"C:\Users\YourUsernameHere\AppData\Local\Temp\1r4TNnfGnwRLdsxPsuK2i8AQHYU"_, where _"1r4TNnfGnwRLdsxPsuK2i8AQHYU"_ is likely a randomly generated string. 
- This might be a result of being a portable electron app that needs to unpack itself, rather than being installed like a traditional app.
- When you pin something to the taskbar in Windows, it's linking directly back to the file that you used to pin. In this case, you are seeing 2 icons because in reality, a new instance of sleek.exe is being unpacked into the directory I mentioned above, then opened. Unfortunately, when you close that instance of sleek.exe, the temporary unpacked directory also gets automatically deleted so you can't just find that .exe and pin that to the taskbar.

I have never built an electron app so I can't actually comment on the fix but I can say that other electron apps that I've used have solved this, I think, by not being completely portable but by doing 1 of 2 things, 

1. Including any necessary files with the application, rather than being a completely portable executable, and/or 
2. Installing those files into somewhere more permanent, like "C:\Users\YourUserName\AppData\Roaming\sleek".

I'm not sure if this helps but it seems the 2nd last comment might be relevant: 
[https://discuss.atom.io/t/how-can-i-get-the-application-path-of-a-portable-electron-app-on-windows/43464/14](https://discuss.atom.io/t/how-can-i-get-the-application-path-of-a-portable-electron-app-on-windows/43464/14
)

Hope this helps to get closer to a solution!

**Comment by blumpcus** [comment]
I've found a temporary solution until @ransome1 can provide a cleaner option!

Steps:

1. Open sleek.exe & keep it open.

2. Find out where sleek has been unpacked to. 
It will certainly be in "C:\Users\YourUsernameHere\AppData\Local\Temp\", but you'll have to search for the folder that contains sleek.exe from there. Quickest way to get here is to press Win+R on your keyboard, type in appdata and press enter. Open up the Local folder and start a search for sleek.exe. 
![image](https://user-images.githubusercontent.com/73550281/114941357-10e4e100-9e11-11eb-8cba-742477dadfc0.png)

3. Once you've found it, copy all the contents within that folder to somewhere else that you'd like to keep sleek in.
It should look like this:
![image](https://user-images.githubusercontent.com/73550281/114941322-04f91f00-9e11-11eb-9bd4-e05844209f0e.png)

4. Close the opened sleek, which will now automatically delete the folder it created in 'appdata'. Unpin sleek from your taskbar if you had tried to do it previously.

5. Open sleek.exe from the new location you moved it to, and then right click on it's icon in the taskbar and hit "Pin to Taskbar".

6. Voila, you should now only have one instance of sleek in the taskbar.

**Comment by ransome1** [comment]
@blumpcus thanks for looking into it. So far I havn't had any chance to investigate and there is lot's more of code refactoring to be done, before I can.

For my understanding: Are you guys using sleek's exe file from Github or do you install it from Windows Store. I' asking because locally on my VM, when I start up sleek from it's sources, it gets put into a permant folder and there is random sub folder created. 

I'm trying to understand if this is something that only occurs on installations from Windows Store.

**Comment by ransome1** [comment]
Alright, I reproduced it on my VM. It only seem to occur on the portable exe. Let's see if I can find a solution to that.

For those of you who are really bugged by it and have the Windows Store installed, you can install the app from there too. Here it does not seem to happen. That could be a temporary fix until I found a proper solution for the portable file.

**Comment by ransome1** [comment]
@shulist, @blumpcus, @intrepidsilence, I looked into it and I'm not sure if I fully understand all these Windows terms, so please help me out. Is it true that it is in the nature of a portable Windows file to create a new temp folder every time it starts up?

In any case I might have found different approach to solve this by not building a portable file, but an installer. From what I learned the installer will install sleek to one persistent path. Like this starting up sleek should not generate another instance of it. I gave it a try on my VM and it seems to work at least for me.

Can you guys please try out the installer and give me some feedback, if this solves this issue? You can download it here: https://github.com/ransome1/sleek/releases/download/v0.9.9/sleek-0.9.9.exe

**Comment by shulist** [comment]
Given all the work to be done in Sleek to deal with other important items I might suggest that this is a somewhat lower priority.  I suppose it would be tidier to only create one instance on the taskbar but if you have to jump through hoops to do this then for me its a very low priority. The fact that Sleek creates a second instance on the taskbar really has no effect on my life. I've noticed some other apps I use also do the same thing (Xming server, Vim, for example) and these also cause me not grief.

**Comment by shulist** [comment]
@ransome1 said `not building a portable file,`

I'd encourage you to consider keeping the portable format. I prefer not having to install smaller apps as its one more issue less to deal with. Further you may want to look at wrapping your portable version of Sleek in the https://portableapps.com/development/portableapps.com_format. If you want I could open a new issue for this outside of this thread, but just wanted to respond to your statement above.

**Comment by ransome1** [comment]
> Given all the work to be done in Sleek to deal with other important items I might suggest that this is a somewhat lower priority. I suppose it would be tidier to only create one instance on the taskbar but if you have to jump through hoops to do this then for me its a very low priority. The fact that Sleek creates a second instance on the taskbar really has no effect on my life. I've noticed some other apps I use also do the same thing (Xming server, Vim, for example) and these also cause me not grief.

As I use Github CI to build the releases, both a portable and an installer can be build and added to the release with no further effort for me. 

> @ransome1 said `not building a portable file,`
> 
> I'd encourage you to consider keeping the portable format. I prefer not having to install smaller apps as its one more issue less to deal with. Further you may want to look at wrapping your portable version of Sleek in the https://portableapps.com/development/portableapps.com_format. If you want I could open a new issue for this outside of this thread, but just wanted to respond to your statement above.

In a nutshell, what would be the advantage of that?

**Comment by shulist** [comment]
Well possibly two things. 1) The portable format PAF is a **widely recognized format**. 2) It has an ecosystem containing 400+ apps currently which might mean **wider distribution for Sleek**. 

However, again, if it involves too much additional work for you  then I'm also happy with the portable format you have already created. Its no big deal to drop Sleek into the PortableApps (PA) folder and configure it run portable within the PA system. 

FYI I currently have about 70 apps running within the PA environment on four different Win10 machines and have installed less than ten apps (those which offer no portable option) using the Win10 registry. Its eliminated many hours wasted at trying to resolve windows registry errors, conflicts and problems.

**Comment by ransome1** [comment]
@intrepidsilence , @blumpcus , the installer is also added in the latest alpha release: https://github.com/ransome1/sleek/releases/tag/v1.0.0-Alpha

I'm looking forward to your feedback, if this solves your issue.

**Comment by intrepidsilence** [comment]
@ransome1 Awesome! The installer fixes this issue for me as I do not have access to the Windows Store on my corpo laptop. Thanks for doing this!

**Comment by ransome1** [comment]
> Well possibly two things. 1) The portable format PAF is a **widely recognized format**. 2) It has an ecosystem containing 400+ apps currently which might mean **wider distribution for Sleek**.
> 
> However, again, if it involves too much additional work for you then I'm also happy with the portable format you have already created. Its no big deal to drop Sleek into the PortableApps (PA) folder and configure it run portable within the PA system.
> 
> FYI I currently have about 70 apps running within the PA environment on four different Win10 machines and have installed less than ten apps (those which offer no portable option) using the Win10 registry. Its eliminated many hours wasted at trying to resolve windows registry errors, conflicts and problems.

@shulist, I stumbled upon a user who added a different todo app to the PortableApps.com project: https://github.com/uroesch/JoplinPortable

As I'm already maintaining the builds on Github, Flathub, Snap and AUR, I won't be heading into this direction, but if becoming a maintainer for sleek on the PortableApps.com project might be something of interest to you, I will of course encourage and support you.
