### ISSUE TITLE
Run in Background and/or minimise to system tray

### ISSUE THREAD

**Issue by blaze1522** [ransome1/sleek#88]
**Problem**: I don't want the GUI to be running when I am not looking.

**Possible Solution**: It would be great if there is run in the background or minimise to the system tray kind of feature where basic actions like new tasks can be added.

**Current Setup**: I use a Gnome shell extension that refers to the same todo.txt so I don't particularly need the system tray thing. But run in the background would be nice.

**Comment by ransome1** [comment]
@blaze1522, thanks for the suggestion which is a nice to have and should not be a big blocker. 

I will check Electrons documentation if this is possible out of the box. 

As for the implementation I suggest this to be a setting because there are definitely users who prefer to have sleek in the task bar and not in the system tray.

**Comment by ransome1** [comment]
Hi @blaze1522, I'm wrapping up this feature at the moment. Before putting it into a release I could need some feedback on the function itself, to see if it works like it's expected from an app that can be minimized to tray and run in the background.

Can I ask you to give it a try, maybe even use it in your production environment, and check in back with your feedback?

You can download it here: https://github.com/ransome1/sleek/releases/tag/v1.0.3

**Comment by blaze1522** [comment]
I played around with the AppImage. Works flawlessly according to me and does everything within the scope of my issue.

Thanks a lot!

**Comment by freder** [comment]
just tested it on the mac:

![sleek](https://user-images.githubusercontent.com/724844/116901483-47f12a00-ac3a-11eb-9031-3d5f5b5ad6ca.gif)

- I first minimize the window (cmd-w), then click the taskbar icon, which restores the window. there is a delay between clicking and the menu appearing though. seems like the menu only shows after the 'restore window' animation finishes.
- clicking the icon (slowly, in succession) seems to toggle minimize/restore. that's not what I expect would happen.
- clicking faster (almost double clicking) on the icon only seems to (re)open the menu

**Comment by ransome1** [comment]
@blaze1522 , thannks for your feedback, I will include it into the next proper release.

@freder, thanks a lot for the video! That's interesting. Especially as MacOS and Linux/Windows apparantly behave differently when it comes to the tray bar.

I have a couple of questions: 
1. For some reasons sleeks windows is minimizing down to the bottom. I assume there is the MacOS dock (task bar)? And if so, is the sleek icon present? Because it is not suppose to (at least on Windows and Linux). 
2. You're pressing CMD+W which does not minimize the window but close it, without quitting the app correct? But the window still goes down to the dock? 
3. What do you expect on MacOS when you (left mouse) click on a tray bar (not the task bar/dock) icon?
4. What do you expect on MacOS when you (right mouse) click on a tray bar icon?
5. What do you expect on MacOS when you double click on a tray bar icon?

**Comment by freder** [comment]
> 1. For some reasons sleeks windows is minimizing down to the bottom. I assume there is the MacOS dock (task bar)? 

yes, that's where my _dock_ is

> And if so, is the sleek icon present? Because it is not suppose to (at least on Windows and Linux).

on the mac I expect any open program – if minimized or not – to show an icon in the dock.

> 2. You're pressing CMD+W which does not minimize the window but close it, without quitting the app correct? But the window still goes down to the dock?

on the mac, in general:
- cmd-w is for closing windows
- cmd-q is for quitting the application (← I am missing this)

with 'minimize to tray bar' _off_:
- cmd-w closes the window
- sleek is still in the dock (therefore running)
- clicking on the dock icon shows the sleek window again, but also an error:

![Screenshot 2021-05-04 at 09 51 24](https://user-images.githubusercontent.com/724844/116974802-ef17a500-acbe-11eb-85f8-b7758da5cbd2.png)

with 'minimize to tray bar' _on_:
- cmd-w does not close, but minimize the window (the shortcut for that is actually cmd-m)
- I also noticed that the app becomes unquittable. right clicking on the dock icon gives you a menu. clicking 'quit' has no effect. (this works with 'minimize to tray bar' _off_)

![Screenshot 2021-05-04 at 09 46 43](https://user-images.githubusercontent.com/724844/116975626-3a7e8300-acc0-11eb-90a0-6f4261d39256.png)


> 3. What do you expect on MacOS when you (left mouse) click on a tray bar (not the task bar/dock) icon?

typically this will show a menu. I have one icon up there though that simply toggles s.th. on or off.

> 4. What do you expect on MacOS when you (right mouse) click on a tray bar icon?

typically this will show (the same) menu.

> 5. What do you expect on MacOS when you double click on a tray bar icon?

a double click isn't really _a thing_ here. it would be interpreted as two single clicks, hence open and close the menu.

**Comment by ransome1** [comment]
Hi @freder, can I ask you to check if the behavior on Mac has been changed with the latest release? https://github.com/ransome1/sleek/releases/tag/v1.0.3

I did some work on the tray function to get it stable on Windows and Linux, unfortunately I don't have a Mac at hand.

**Comment by ransome1** [comment]
I hope all MacOS issues are fixed in https://github.com/ransome1/sleek/releases/tag/v1.0.4

If not please post here and I will reopen this issue.
